### ISSUE TITLE
change structure of git repository

### ISSUE THREAD

**Issue by 1360151219** [LZpenguin/pic-edit#1]
不好意思，readme里面有点地方错了 现在改好了 你可以去看一看
![image](https://user-images.githubusercontent.com/74706849/134531065-f813bc69-3877-43da-a0de-984c24f5a45d.png)
![image](https://user-images.githubusercontent.com/74706849/134531091-e212ab04-358c-463d-8591-646ffd9e5563.png)

**Comment by LZpenguin** [comment]
已修正
