### ISSUE TITLE
use md extension instead of txt

### ISSUE THREAD

**Issue by Chronostasys** [LZpenguin/pic-edit#2]
rename `schedule/日志.txt` **to** `schedule/日志.md` and open [the link](https://github.com/LZpenguin/pic-edit/blob/main/schedule/%E6%97%A5%E5%BF%97.md) , you may understand what I mean.
------

**Comment by LZpenguin** [comment]
copy,already fixed

**Comment by Chronostasys** [comment]
glad to hear that, then you can close this issue
